package resp

const (
	CodeInternal         = "INTERNAL_ERROR"
	CodeInvalidBody      = "INVALID_BODY"
	CodeInvalidParam     = "INVALID_PARAM"
	CodeInvalidCode      = "INVALID_CODE"
	CodeSendFailed       = "SEND_FAILED"
	CodeNotFound         = "NOT_FOUND"
	CodeConflict         = "CONFLICT"
	CodeUserExists       = "USER_EXISTS"
	CodePhoneExists      = "PHONE_EXISTS"
	CodeEmailExists      = "EMAIL_EXISTS"
	CodeAuthRequired     = "AUTH_REQUIRED"
	CodeAuthInvalid      = "AUTH_TOKEN_INVALID"
	CodeAuthForbidden    = "AUTH_INSUFFICIENT_PRIVILEGE"
	CodeAuthDisabled     = "AUTH_USER_DISABLED"
	CodeAuthBanned       = "AUTH_USER_BANNED"
	CodeAuthFrozen       = "AUTH_USER_FROZEN"
	CodeRateLimited      = "RATE_LIMITED"
	CodeWechatAuthFailed = "WECHAT_AUTH_FAILED"
	CodeQrcodeExpired    = "QRCODE_EXPIRED"
	CodeQrcodeNotFound   = "QRCODE_NOT_FOUND"
)

const (
	MsgListUsersFailed    = "failed to list users"
	MsgCreateUserFailed   = "failed to create user"
	MsgLoginFailed        = "invalid username or password"
	MsgRegisterFailed     = "failed to register"
	MsgUserExists         = "username already exists"
	MsgPhoneExists        = "phone number already exists"
	MsgEmailExists        = "email already exists"
	MsgRefreshFailed      = "invalid refresh token"
	MsgAuthRequired       = "authorization required"
	MsgAuthInvalid        = "invalid token"
	MsgAuthForbidden      = "insufficient privilege"
	MsgAuthDisabled       = "user is disabled"
	MsgAuthBanned         = "account has been banned"
	MsgAuthFrozen         = "account has been frozen"
	MsgRateLimited        = "too many requests"
	MsgInvalidParam       = "invalid parameter"
	MsgInvalidCode        = "invalid verification code"
	MsgSendFailed         = "failed to send verification code"
	MsgListCanvasFailed   = "failed to list canvases"
	MsgGetCanvasFailed    = "failed to get canvas"
	MsgSaveCanvasFailed   = "failed to save canvas"
	MsgDeleteCanvasFailed = "failed to delete canvas"
	MsgCanvasNotFound     = "canvas not found"
	MsgInvalidCanvasID    = "invalid canvas id"
	MsgInvalidDocument    = "invalid canvas document"
	MsgListMaterialFailed = "failed to list materials"
	MsgSaveMaterialFailed = "failed to save material"
	MsgCanvasAccessDenied = "canvas access denied"
	MsgCanvasPending      = "canvas is pending review"
	MsgSubmitCanvasFailed = "failed to submit canvas for review"
	MsgAuditFailed        = "failed to audit canvas"
	MsgListVipPlanFailed  = "failed to list vip plans"
	MsgSaveVipPlanFailed  = "failed to save vip plan"
	MsgInvalidVipPlan     = "invalid vip plan"
	MsgSubscribeFailed    = "failed to subscribe"
	MsgListNotifyFailed   = "failed to list notifications"
	MsgWechatAuthFailed   = "wechat authentication failed"
	MsgQrcodeExpired      = "qrcode expired"
	MsgQrcodeNotFound     = "qrcode not found"
)
