package resp

const (
	CodeInternal      = "INTERNAL_ERROR"
	CodeInvalidBody   = "INVALID_BODY"
	CodeInvalidParam  = "INVALID_PARAM"
	CodeNotFound      = "NOT_FOUND"
	CodeConflict      = "CONFLICT"
	CodeUserExists    = "USER_EXISTS"
	CodeAuthRequired  = "AUTH_REQUIRED"
	CodeAuthInvalid   = "AUTH_TOKEN_INVALID"
	CodeAuthForbidden = "AUTH_INSUFFICIENT_PRIVILEGE"
	CodeAuthDisabled  = "AUTH_USER_DISABLED"
	CodeRateLimited   = "RATE_LIMITED"
)

const (
	MsgListUsersFailed    = "failed to list users"
	MsgCreateUserFailed   = "failed to create user"
	MsgLoginFailed        = "invalid username or password"
	MsgRegisterFailed     = "failed to register"
	MsgUserExists         = "username already exists"
	MsgRefreshFailed      = "invalid refresh token"
	MsgAuthRequired       = "authorization required"
	MsgAuthInvalid        = "invalid token"
	MsgAuthForbidden      = "insufficient privilege"
	MsgAuthDisabled       = "user is disabled"
	MsgRateLimited        = "too many requests"
	MsgListCanvasFailed   = "failed to list canvases"
	MsgGetCanvasFailed    = "failed to get canvas"
	MsgSaveCanvasFailed   = "failed to save canvas"
	MsgDeleteCanvasFailed = "failed to delete canvas"
	MsgCanvasNotFound     = "canvas not found"
	MsgInvalidCanvasID    = "invalid canvas id"
	MsgInvalidDocument    = "invalid canvas document"
	MsgListMaterialFailed = "failed to list materials"
	MsgSaveMaterialFailed = "failed to save material"
	MsgCanvasAccessDenied = "canvas access denied"
	MsgCanvasPending      = "canvas is pending review"
	MsgSubmitCanvasFailed = "failed to submit canvas for review"
	MsgAuditFailed        = "failed to audit canvas"
	MsgListVipPlanFailed  = "failed to list vip plans"
	MsgSaveVipPlanFailed  = "failed to save vip plan"
	MsgInvalidVipPlan     = "invalid vip plan"
	MsgSubscribeFailed    = "failed to subscribe"
	MsgListNotifyFailed   = "failed to list notifications"
)
